sudo: required
install: true
language: java
dist: xenial

services:
  - docker

env:
  - MAVEN_COMMON_OPTS="-B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn"

before_install:
  - curl -s "https://get.sdkman.io" | bash
  - source "$HOME/.sdkman/bin/sdkman-init.sh"
  - mkdir -p "$HOME/.sdkman/etc"
  - echo "sdkman_auto_answer=true" > "$HOME/.sdkman/etc/config"
  - echo "sdkman_auto_selfupdate=true" >> "$HOME/.sdkman/etc/config"
  - sdk version
  - sdk install java 8.0.242.hs-adpt

script:
  - sdk use java 8.0.242.hs-adpt
  - java -version
  - ./mvnw clean install $MAVEN_COMMON_OPTS

deploy:
  provider: script
  script: ./mvnw clean deploy $MAVEN_COMMON_OPTS -DskipTests --settings etc/mvn-deploy-settings.xml
  skip_cleanup: true 
  on:
    branch: master
    condition: $TRAVIS_PULL_REQUEST = "false"
    
